version: '3.8'

services:
  app:
    image: portfoliomanagement:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__PORTFOLIO=Server=db;Database=teste;User=sa;Password=Your_password123;MultipleActiveResultSets=true;TrustServerCertificate=true;
    
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./sql-scripts:/var/opt/mssql/scripts


volumes:
  sql_data:
